spring:
  datasource:
    # ↓ ECS 태스크 환경변수/시크릿으로 주입됨 (필수)
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver